# Config specific
device: "cuda"
num_workers: 8

# Dataset configuration
dataset:
  type: "CIFAR10"
  root: "./data/cifar10"
  download: true

# Model configuration
model:
  type: "AlexNet"
  in_channel: 3
  out_channel: 10

# Hyperparameters
batch_size: 128
epochs: 5
clip_grad_norm: 1.0

# Optimizer configuration
optimizer:
  type: "SGD"
  lr: 0.03
  momentum: 0.9
  weight_decay: 0.0

# Criterion (loss function) configuration
criterion:
  type: "CrossEntropyLoss"
  label_smoothing: 0.1

# File save/logs settings
run_dir: "runs/alexnet_cifar10_exp1"
tb_dir: "tb-output"
max_keep: 2