# Config specific
device: "cuda"
num_workers: 8

# Hyperparameters
batch_size: 4096
epochs: 90

# Dataset configuration
dataset:
  type: "ImageNet"
  root: "./data/ImageNet"

# Model configuration
model:
  type: "ViT"
  img_size: 224
  in_channels: 3
  patch_size: 16
  nb_blocks: 11
  embed_dim: 768
  num_heads: 12
  out_classes: 1000

# Optimizer configuration
optimizer:
  type: "Adam"
  betas: [0.9, 0.999]
  lr: 0.001
  weight_decay: 0.03

# Criterion (loss function) configuration
criterion:
  type: "CrossEntropyLoss"
  label_smoothing: 0.1

# Learning rate scheduler configuration
scheduler:
  type: "LinearLR"
  start_factor: 1
  end_factor: 0.333333333333
  total_iters: 10

# File save/logs settings
run_dir: "runs/vit_imagenet_exp1"
tb_dir: "/workspace"
max_keep: 1