# Device configuration
device: "cuda"
num_workers: 4

# Dataset configuration
dataset:
  type: "CIFAR10"
  root: "./data/cifar10"
  download: true

  train_transforms:
    preset: "cifar10_basic"
    additional:
      - type: "HorizontalFlip"
        p: 0.5
  test_transforms: "cifar10_basic"

# Model configuration
model:
  type: "DDPM"

  in_channels: 3
  out_channels: 3
  model_channels: 128
  channel_mult: [1, 2, 2, 2]
  num_res_blocks: 2
  time_emb_dim: 128
  dropout: 0.1

  # Diffusion parameters
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

# Training hyperparameters
batch_size: 128
epochs: 500

# Optimizer configuration
optimizer:
  type: "Adam"
  lr: 0.0002

# Sampling/Evaluation parameters
num_sample_images: 64
sample_every_n_epochs: 10
sample_image_size: 32

# File save/logs settings
run_dir: "runs/ddpm_cifar10"
tb_dir: "runs/ddpm_cifar10/tb-output"
max_keep: 1
no_save: false
